
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'nonassocIFXnonassocELSEleftSUMARESTAleftMULTDIVAND ASIGNACION CHAR COMA COMILLAS COMILLAS_S DER_BRACE DER_PAREN DIV ELSE EQ FLOAT FLOAT_CONST GE GT ID IF INT INT_CONST IZQ_BRACE IZQ_PAREN LE LT MOD MULT NEQ NOT OR PUNTO_COMA RESTA RETURN SUMA WHILEprogram : lista_sentenciaslista_sentencias : lista_sentencias sentencialista_sentencias : sentenciasentencia : INT ID PUNTO_COMA\n                | INT ID ASIGNACION expr PUNTO_COMAsentencia : ID ASIGNACION expr PUNTO_COMAsentencia : IF IZQ_PAREN expr DER_PAREN sentencia %prec IFX\n                 | IF IZQ_PAREN expr DER_PAREN sentencia ELSE sentenciasentencia : WHILE IZQ_PAREN expr DER_PAREN sentenciasentencia : IZQ_BRACE lista_sentencias DER_BRACEexpr : expr SUMA termino\n            | expr RESTA terminotermino : termino MULT factor\n            | termino DIV factorexpr : terminotermino : factorfactor : INT_CONST\n              | FLOAT_CONSTfactor : IDfactor : IZQ_PAREN expr DER_PAREN'
    
_lr_action_items = {'INT':([0,2,3,8,9,14,15,26,28,34,35,36,42,43,44,45,],[4,4,-3,4,-2,4,-4,-10,-6,4,4,-5,-7,-9,4,-8,]),'ID':([0,2,3,4,8,9,11,12,13,14,15,16,23,26,28,29,30,31,32,34,35,36,42,43,44,45,],[5,5,-3,10,5,-2,17,17,17,5,-4,17,17,-10,-6,17,17,17,17,5,5,-5,-7,-9,5,-8,]),'IF':([0,2,3,8,9,14,15,26,28,34,35,36,42,43,44,45,],[6,6,-3,6,-2,6,-4,-10,-6,6,6,-5,-7,-9,6,-8,]),'WHILE':([0,2,3,8,9,14,15,26,28,34,35,36,42,43,44,45,],[7,7,-3,7,-2,7,-4,-10,-6,7,7,-5,-7,-9,7,-8,]),'IZQ_BRACE':([0,2,3,8,9,14,15,26,28,34,35,36,42,43,44,45,],[8,8,-3,8,-2,8,-4,-10,-6,8,8,-5,-7,-9,8,-8,]),'$end':([1,2,3,9,15,26,28,36,42,43,45,],[0,-1,-3,-2,-4,-10,-6,-5,-7,-9,-8,]),'DER_BRACE':([3,9,14,15,26,28,36,42,43,45,],[-3,-2,26,-4,-10,-6,-5,-7,-9,-8,]),'ASIGNACION':([5,10,],[11,16,]),'IZQ_PAREN':([6,7,11,12,13,16,23,29,30,31,32,],[12,13,23,23,23,23,23,23,23,23,23,]),'PUNTO_COMA':([10,17,18,19,20,21,22,27,37,38,39,40,41,],[15,-19,28,-15,-16,-17,-18,36,-11,-12,-13,-14,-20,]),'INT_CONST':([11,12,13,16,23,29,30,31,32,],[21,21,21,21,21,21,21,21,21,]),'FLOAT_CONST':([11,12,13,16,23,29,30,31,32,],[22,22,22,22,22,22,22,22,22,]),'ELSE':([15,26,28,36,42,43,45,],[-4,-10,-6,-5,44,-9,-8,]),'MULT':([17,19,20,21,22,37,38,39,40,41,],[-19,31,-16,-17,-18,31,31,-13,-14,-20,]),'DIV':([17,19,20,21,22,37,38,39,40,41,],[-19,32,-16,-17,-18,32,32,-13,-14,-20,]),'SUMA':([17,18,19,20,21,22,24,25,27,33,37,38,39,40,41,],[-19,29,-15,-16,-17,-18,29,29,29,29,-11,-12,-13,-14,-20,]),'RESTA':([17,18,19,20,21,22,24,25,27,33,37,38,39,40,41,],[-19,30,-15,-16,-17,-18,30,30,30,30,-11,-12,-13,-14,-20,]),'DER_PAREN':([17,19,20,21,22,24,25,33,37,38,39,40,41,],[-19,-15,-16,-17,-18,34,35,41,-11,-12,-13,-14,-20,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'lista_sentencias':([0,8,],[2,14,]),'sentencia':([0,2,8,14,34,35,44,],[3,9,3,9,42,43,45,]),'expr':([11,12,13,16,23,],[18,24,25,27,33,]),'termino':([11,12,13,16,23,29,30,],[19,19,19,19,19,37,38,]),'factor':([11,12,13,16,23,29,30,31,32,],[20,20,20,20,20,20,20,39,40,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> lista_sentencias','program',1,'p_program','parser.py',17),
  ('lista_sentencias -> lista_sentencias sentencia','lista_sentencias',2,'p_lista_sentencias_multiple','parser.py',21),
  ('lista_sentencias -> sentencia','lista_sentencias',1,'p_lista_sentencias_simple','parser.py',25),
  ('sentencia -> INT ID PUNTO_COMA','sentencia',3,'p_sentencia_declaracion','parser.py',29),
  ('sentencia -> INT ID ASIGNACION expr PUNTO_COMA','sentencia',5,'p_sentencia_declaracion','parser.py',30),
  ('sentencia -> ID ASIGNACION expr PUNTO_COMA','sentencia',4,'p_sentencia_asignacion','parser.py',37),
  ('sentencia -> IF IZQ_PAREN expr DER_PAREN sentencia','sentencia',5,'p_sentencia_if','parser.py',41),
  ('sentencia -> IF IZQ_PAREN expr DER_PAREN sentencia ELSE sentencia','sentencia',7,'p_sentencia_if','parser.py',42),
  ('sentencia -> WHILE IZQ_PAREN expr DER_PAREN sentencia','sentencia',5,'p_sentencia_while','parser.py',51),
  ('sentencia -> IZQ_BRACE lista_sentencias DER_BRACE','sentencia',3,'p_sentencia_bloque','parser.py',56),
  ('expr -> expr SUMA termino','expr',3,'p_expr_binaria','parser.py',60),
  ('expr -> expr RESTA termino','expr',3,'p_expr_binaria','parser.py',61),
  ('termino -> termino MULT factor','termino',3,'p_termino_binario','parser.py',65),
  ('termino -> termino DIV factor','termino',3,'p_termino_binario','parser.py',66),
  ('expr -> termino','expr',1,'p_expr_termino','parser.py',70),
  ('termino -> factor','termino',1,'p_termino_factor','parser.py',74),
  ('factor -> INT_CONST','factor',1,'p_factor_numero','parser.py',78),
  ('factor -> FLOAT_CONST','factor',1,'p_factor_numero','parser.py',79),
  ('factor -> ID','factor',1,'p_factor_id','parser.py',83),
  ('factor -> IZQ_PAREN expr DER_PAREN','factor',3,'p_factor_expr','parser.py',87),
]
